### ISSUE TITLE
API Implementation

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/VidBits#2]
You did a good job with your API implementation.  You had routes created for all CRUD endpoints.  You also included model validation in the appropriate endpoints and handled error cases well.  There were some areas in your code however, that could be made more efficient.  For instance, take the following snippet:

https://github.com/mohaldev/VidBits/blob/123c97c3ee36556a92dd0b3930ed133dae0ea388/routes/videos.js#L23-L30

Here you are checking error cases.  The handler code for these conditions if almost identical with the exception of the value of the property "error" in the response.  I would recommend seeing how you could "DRY" that code up by only called that error response once and injecting the proper "error" value dynamically.  Other than that, really nice work!

**Comment by mohaldev** [comment]
Good point!
