### ISSUE TITLE
Summary - Meets Expectations

### ISSUE THREAD

**Issue by tbergen1** [mohaldev/VidBits#5]
Overall, you did well with this project.  You model implementation was spot on, including all of the relevant information and requirements to create a robust model.  You also did well implementing your API and views.  All of the tests seemed to have been included as well, though I was unable to run them due to some weird permissions errors that I wold recommend fixing.  The other area of improvement I would suggest would be to "DRY" your code up a bit by looking at ways to avoid repeating similar blocks of code like you were doing with error handling in your route code.  Other than that, nice work!

**Comment by mohaldev** [comment]
Thanks for the feedabck. I will look deeper into the permissions issue. Must be something that I have to dig deeper. Will check this.
